version: '3.4'

services:
  orderbook.webapi:
    image: orderbook.webapi
    build:
      context: .
      dockerfile: OrderBook.WebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionOptions__ConnectionString=Host=orderbook.database;Port=5432;Database=OrderBook;Username=postgres;Password=qwerty1
    depends_on:
      - orderbook.database
    ports: 
      - "8080:8080"
      - "8081:8081"

  orderbook.database:
    image: postgres:latest
    container_name: orderbook.database
    environment:
      POSTGRES_DB: OrderBook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5431:5432

volumes:
  postgres_data:
